INSERT INTO cabs (
    name,
    slug,
    cab_type,
    description,
    city,
    state,
    country,
    seating_capacity,
    contact_phone,
    contact_email,
    base_fare,
    per_km_rate,
    per_hour_rate,
    status
) VALUES
(
    'Hyderabad City Cab',
    'hyderabad-city-cab',
    'SEDAN',
    'Comfortable sedan cab for local travel in Hyderabad.',
    'Hyderabad',
    'Telangana',
    'India',
    4,
    '9876543220',
    'hyderabad@cabs.example',
    100.00,
    18.00,
    250.00,
    'ACTIVE'
),
(
    'Bengaluru Airport Cab',
    'bengaluru-airport-cab',
    'SUV',
    'SUV cab suitable for airport transfers and group travel in Bengaluru.',
    'Bengaluru',
    'Karnataka',
    'India',
    6,
    '9876543221',
    'bengaluru@cabs.example',
    200.00,
    22.00,
    350.00,
    'ACTIVE'
),
(
    'Jaipur Tourist Cab',
    'jaipur-tourist-cab',
    'HATCHBACK',
    'Affordable cab for local sightseeing and tourist travel in Jaipur.',
    'Jaipur',
    'Rajasthan',
    'India',
    4,
    '9876543222',
    'jaipur@cabs.example',
    80.00,
    15.00,
    220.00,
    'ACTIVE'
);